version: "3.8"

services:
  app-sgd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sgd_firmas_app
    ports:
      - "${PORT:-8080}:80"
    # Carga automáticamente todas las variables del archivo .env
    env_file:
      - .env
    volumes:
      - ./db_sgd_firmas.sqlite:/var/www/html/db_sgd_firmas.sqlite
      - ./archivos_sgd:/var/www/html/archivos_sgd
    restart: always
